a= int(input(('1st number= ')))
b= int(input(('2nd number= ')))
print('Your Number=',a+b)
print('Your Number=',a-b)
print('Your Number=',a*b)
print('Your Number=',a/b)
print('Your Number=',a//b)
print('Your Number=',a%b)
